### ISSUE TITLE
DistTC

### ISSUE THREAD

**Issue by vishweshjatala** [IntelligentSoftwareSystems/Galois#108]
1. Clean up the code
2. Merge to Dist-Dev branch and finally to the master branch.

**Comment by vishweshjatala** [comment]
Upgraded the code, builds fine, verified the correctness. This issue has been addressed in https://github.com/IntelligentSoftwareSystems/Galois/issues/148 and can be closed.

**Comment by roshandathathri** [comment]
Requires code for CPUs before we can close this issue.

**Comment by ddn0** [comment]
I assume we are keeping both `tc` and `tc_mine`? If so, how hard would it be to address

https://github.com/IntelligentSoftwareSystems/Galois/blame/7fc4836a55ef299a37cbacef86881eb6f9f11d0a/lonestar/libdistbench/include/DistMiningBenchStart.h#L20

which calls for unifying `DistBenchStart.h` and `DistMiningBenchStart.h`? `tc` is the only application that uses `DistMiningBenchStart.h` at the moment.

**Comment by l-hoang** [comment]
The issue with merging at the moment that comes to the top of my head is that GluonSubstrate/GluonEdgeSubstrate and MiningGraph/NewGeneric (CuSP headers) includes **if I recall correctly** might have conflicting namespaces on the GPU end. It's been a while since I've taken a look at the code however.

Otherwise it shouldn't be that hard, but it's one of those things where I won't know until I try. I don't have the cycles to do it at this moment in time, though.
