### ISSUE TITLE
Distinguish names of properties and actions in loop traits

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#280]
@bozhiyou :
> Just noticed this in the tutorial: should no_pushes also be disable_context_push or something for better consistency?

@roshandathathri :
> That is a property, not an action. We should make it consistent later/separately. I'm not sure if everything can be an action. In this case, I think it's better to use has_no_pushes to indicate that it is property.

**Comment by bozhiyou** [comment]
`has_no_pushes` works for me, but if it's though of as a property, then IMO it should be `galois::pushes<false>` like `galois::chunk_size<val>` or `galois::wl<val>` since they are also properties (?), which is not good though. I personally prefer to think of it as an action as well like `disable_conflict_detection`.

**Comment by roshandathathri** [comment]
I like galois::pushes<false>

**Comment by insertinterestingnamehere** [comment]
A few releases ago I put together some code for making it so that we can configure loop and graph options using things like `pushes<false>` and so that we can pass the options in any order. I can look at reviving that work if people are interested. Not for this release though.

**Comment by roshandathathri** [comment]
Yes, not for this release. Thanks, Ian!
