### ISSUE TITLE
Set default visibility to hidden and explicitly mark functions for export

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#303]
It is probably good practice to reduce namespace pollution by explicitly exporting symbols. I believe this will also reduce object sizes when there are a lot of template instantiations.

**Comment by insertinterestingnamehere** [comment]
This is a really good idea, though the fix may be a little time consuming. Explicitly exporting symbols is a really good thing because it helps us explicitly distinguish between header-only API, shared object ABI, and internal APIs. This is also one of the key things we'd should fix if we ever want things to actually work well on Windows (not just with WSL).
