### ISSUE TITLE
std::unary_function: Removed Feature in C++17

### ISSUE THREAD

**Issue by bozhiyou** [IntelligentSoftwareSystems/Galois#322]
`std::unary_function` and maybe the likes are still used somewhere in the release, which have been deprecated in C++11 and removed from C++17. No idea why they didn't cause issues though, I think we should retire them in the release anyways. The substitution for function adaptors may be `std::function`.

**Comment by insertinterestingnamehere** [comment]
Thanks for finding this. The right fix may just be to remove it entirely. As far as I can tell it just adds a base class with some extra type information. It was probably needed prior to C++11 because there weren't template metaprogramming techniques that allow you to just infer things like function arity, argument types, and return type. As to why we didn't see this before, it must be used exclusively in templates that aren't actually used anywhere in our apps. Compilers overlook all kinds of things in unused templates. There's some reason for that in the standard, but I don't remember it off the top of my head.

**Comment by insertinterestingnamehere** [comment]
Looks like libstdc++ still exposes these types in C++17 (https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libstdc%2B%2B-v3/include/bits/stl_function.h#L105). Idk why though. I'm checking to see if we actually need them.

**Comment by insertinterestingnamehere** [comment]
Ditto for libc++: https://github.com/llvm/llvm-project/blob/c8ad8686ac072fb35862f4d5e09cb1ab91a15a8e/libcxx/include/utility#L961.
