### ISSUE TITLE
What is the format of mastersFile?

### ISSUE THREAD

**Issue by Sanzo00** [IntelligentSoftwareSystems/Galois#395]
I want to specify the master for each host, I know this needs to read from the masterFile, but what is the format of the masterFile?

https://github.com/IntelligentSoftwareSystems/Galois/blob/59d5aa54b4a7b6594660bb1b18b83ae6875b954c/libcusp/include/galois/graphs/NewGeneric.h#L190

https://github.com/IntelligentSoftwareSystems/Galois/blob/59d5aa54b4a7b6594660bb1b18b83ae6875b954c/libcusp/include/galois/graphs/DistributedGraph.h#L416-L428

For example, the input has 6 vertices (0-5). I want to specify that the range of host 0 is [0, 2], and the range of host 1 is [3, 5]. What should the masterFile look like?

**Comment by l-hoang** [comment]
I wouldn't depend on that code path working at this point as it's been years since it has been in use + I don't
think the method of passing it in is exposed via the CuSP interface anymore.

In addition, that code path that you point out is specifying *readers* for hosts, not masters; it was used
to force certain hosts to be responsible for reading masters to avoid imbalance during partitioning. The
path for specifying compute masters has been dropped in the current code.
