### ISSUE TITLE
Easiest / fastest way to filter out edges of interest before starting algo execution? 

### ISSUE THREAD

**Issue by jmftrindade** [IntelligentSoftwareSystems/Galois#41]
Hi there! This is not really an issue, more of an API question: in the lonestar BFS example:

https://github.com/IntelligentSoftwareSystems/Galois/blob/8fa18faea4cd0df855ae5d78a6aa2501c4cca6cd/lonestar/bfs/bfs.cpp#L410

Does Galois offer a parallel filter construct that would allow me to remove edges matching a predicate of interest before executing the main BFS loop? 

Thanks!
Joana

**Comment by insertinterestingnamehere** [comment]
@jmftrindade, if I've understood correctly, you want to use some subset of the nodes/edges from some graph for a parallel computation. I'm not aware of any special API to do that. There are some ways to do that by hand though.

One way to do that is to use a `morph_graph`. Here's a usage example from the tutorial: https://github.com/IntelligentSoftwareSystems/Galois/blob/8fa18faea4cd0df855ae5d78a6aa2501c4cca6cd/lonestar/tutorial_examples/TorusConstruction.cpp#L30. It has APIs that allow you to add/delete edges from the graph in parallel. You could create a `morph_graph` and then delete the edges you want removed.

Another thing you could do is build an entirely new graph based on the old one using `galois::graphs::FileGraphWriter`. The interface is a bit rough around the edges, but there's an example at https://github.com/IntelligentSoftwareSystems/Galois/blob/8fa18faea4cd0df855ae5d78a6aa2501c4cca6cd/lonestar/matching/bipartite-mcm.cpp#L1007. This has the advantage that it won't force you to use `morph_graph` for your main parallel loop. Depending on what you're doing, that may or may not be a big deal.

One more alternative would be to just add a bool flag to the edge or node data that you want to ignore and then check that as the algorithm progresses. If what you're doing requires conflict detection, it may be beneficial to do some of the lock management manually to avoid spurious conflicts between work items that only conflict because they both look at a node that was flagged as excluded.

**Comment by jmftrindade** [comment]
This is super helpful, thanks!

**Comment by l-hoang** [comment]
Closing issue unless there are pending questions at which point it will be re-opened.
