### ISSUE TITLE
NodeIterator and EdgeIterator for TriangleCounting yield different results

### ISSUE THREAD

**Issue by vaastav** [IntelligentSoftwareSystems/Galois#47]
I am trying to run TriangleCounting on the cit-Patents dataset and I get 2 different numbers for the NodeIterator and EdgeIterator algorithms!
I was wondering why that is? 

For reference, for the NodeIterator I get 261897 triangles. For the EdgeIterator I get 188649 triangles.

Any explanation would be helpful!

**Comment by l-hoang** [comment]
Hello.

Are you using a symmetric version of cit-Patents? (i.e. every directed edge has one in the reverse direction as well)

If not, you may get differing results between the two algorithms.

Regards,
Loc Hoang

**Comment by vaastav** [comment]
I am using the out-of-box version which I think is a directed graph!

**Comment by l-hoang** [comment]
That would probably explain it (I tested myself with an directed graph and found similar issues to what you are describing).

You can use Galois's graph-convert utility to make it symmetric. After that you should use the same utility to clean the graph (i.e. remove multiedges/self-loops as those can mess with the triangle count number since it expects a clear symmetric graph).

Let me know how that goes.

Regards,
Loc Hoang

**Comment by vaastav** [comment]
Hmm ok I can try that.
In the meantime I was trying a simple graph with the following edges:

0 -> 1
1 -> 2
2 -> 0
3 -> 4
3 -> 5
4 -> 5

Both the NodeIterator and EdgeIterator give the result as 0 triangles. But when I add the reverse edges, the result switches to 2 for both.
So, it seems like that the behavior for a non-symmetric graph or for a semi-symmetric graph is not correct/undefined.

**Comment by l-hoang** [comment]
Yes; the README specifies that a symmetric graph is required.
